config-version = 2

persistent-workspaces = ["1", "2"]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

default-root-container-layout = 'tiles'

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

[key-mapping]
    preset = 'qwerty'

[mode.main.binding]
    alt-h = 'focus --boundaries-action wrap-around-the-workspace right'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace left'

    alt-shift-h = 'move right'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move left'

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-w = 'close'

    alt-p = 'workspace prev'
    alt-n = 'workspace next'

    alt-space = 'workspace-back-and-forth'

    alt-semicolon = 'mode service'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'

    alt-r = 'mode resize'
    alt-shift-w = 'mode workspace'

[mode.resize.binding]
    l = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    h = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[mode.workspace.binding]
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-workspace-to-monitor 1'
    alt-shift-2 = 'move-workspace-to-monitor 2'
    alt-shift-3 = 'move-workspace-to-monitor 3'
    alt-shift-4 = 'move-workspace-to-monitor 4'
    alt-shift-5 = 'move-workspace-to-monitor 5'
    alt-shift-6 = 'move-workspace-to-monitor 6'
    alt-shift-7 = 'move-workspace-to-monitor 7'
    alt-shift-8 = 'move-workspace-to-monitor 8'
    alt-shift-9 = 'move-workspace-to-monitor 9'
    alt-shift-0 = 'move-workspace-to-monitor 10'
    enter = 'mode main'
    esc = 'mode main'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    v = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

    f = ['fullscreen', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    backspace = ['close-all-windows-but-current', 'mode main']

[[on-window-detected]]
    if.app-name-regex-substring = 'finder'
    run = 'layout floating'

[[on-window-detected]]
    if.app-name-regex-substring = 'messages'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'org.mitchellh.ghostty'
    run = 'workspace 1'

[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'secondary'

